#!/bin/sh
cd ${0%/*} || exit 1 # Run from this directory

# Source tutorial clean functions
. $WM_PROJECT_DIR/bin/tools/CleanFunctions

cleanCase
rm -rf \
    0  \
    0/cellToRegion \
    0/*/cellToRegion \
    constant/*/polyMesh \
    constant/extendedFeatureEdgeMesh \
    constant/triSurface/*.eMesh \
    system/U_termi* \
    system/fif* \
    system/fis* \
    system/C* 
# ----------------------------------------------------------------- end-of-file
